language: node_js
before_script: "make test-prepare"
node_js:
  - 0.6
  - 0.8
  - 0.9
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
    - "irc.freenode.org#docpad-dev"
  email:
    recipients:
      - balutil@bevry.me