sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
  - node_js: '0.10'
  - node_js: '10'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: LrhPsH1WCLmM466G8YjwpY8HFBL9dKiffNakA3vc8Lgz9UXViIgz5LwjFnNwCZuStyYtyBF8O6gMqNtNTyZdqVYh2ZaYxwNcQEKDVINb0UXZpAHU3u1V4risHQv7Qzq2/ew+Iebdkv5xkwz8hspYKwLN03vMDz3DbzsQgwsjtkM=
  email:
    recipients:
      secure: CnYMNACfoTuVowtMSyzGf/c24t59zEirhfRPPUzl1A/ApMZ5dppwQo3UrHQmT+77WVAMYqnHR2kVORo4BPcbFPzhjHOoeyZbZK3ByLZEqZmiQNVYCX0aYtCeN29CeGgEm/fPU0U3HekL/vp0HpdggvIdtbTXq/z2sqLe8sXnHuc=
